repos:
   - repo: https://github.com/astral-sh/ruff-pre-commit
     rev: v0.15.6
     hooks:
        - id: ruff-check  # Linter
          args: [--fix]  # Ensure fixes are applied
        - id: ruff-format  # Formatter
   -  repo: https://github.com/pre-commit/mirrors-mypy
      rev: ''  # Use the sha / tag you want to point at
      hooks:
      -   id: mypy
          args: [--strict, --ignore-missing-imports, --explicit-package-bases]
          additional_dependencies: [tokenize-rt==3.2.0, pydantic, fastapi]